### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ClaytonSibanda** [chrisgrande/django-trix#2]
Hi
How do i install this to my django project?

**Comment by chrisgrande** [comment]
It will probably need to be installed manually, add the **trix** folder to your Django project as another app, and then add `trix` to your `settings.py` file.

I haven't worked on the pip installer from the original project.

**Comment by chrisgrande** [comment]
You can install my master branch in your project with:
`pip install https://github.com/chrisgrande/django-trix/archive/master.tar.gz`
